-- MySQL Script generated by MySQL Workbench
-- 12/11/14 18:43:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bjs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bjs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bjs` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `bjs` ;

-- -----------------------------------------------------
-- Table `bjs`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjs`.`Student` (
  `PKey` CHAR(36) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `Forename` VARCHAR(45) NOT NULL,
  `Sex` ENUM('Male','Female') NOT NULL,
  `YearOfBirth` YEAR NOT NULL,
  PRIMARY KEY (`PKey`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bjs`.`Competition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjs`.`Competition` (
  `StudentPKey` CHAR(36) NOT NULL,
  `Year` YEAR NOT NULL,
  `Sprint` FLOAT NULL,
  `Jump` FLOAT NULL,
  `Throw` FLOAT NULL,
  `MiddleDistance` FLOAT NULL,
  PRIMARY KEY (`StudentPKey`, `Year`),
  CONSTRAINT `StudentPKey`
    FOREIGN KEY (`StudentPKey`)
    REFERENCES `bjs`.`Student` (`PKey`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;
CREATE INDEX `StudentPKeyINDEX` ON `bjs`.`Competition` (`StudentPKey` ASC);

SHOW WARNINGS;
CREATE INDEX `YearINDEX` ON `bjs`.`Competition` (`Year` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bjs`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjs`.`Course` (
  `PKey` CHAR(36) NOT NULL,
  `CourseName` CHAR(3) NOT NULL,
  PRIMARY KEY (`PKey`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `CourseNameUNIQUE` ON `bjs`.`Course` (`CourseName` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bjs`.`DisciplineMeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjs`.`DisciplineMeta` (
  `CoursePKey` CHAR(36) NOT NULL,
  `Year` YEAR NOT NULL,
  `GameType` ENUM('Competition','Traditional') NOT NULL,
  `MaleSprintPKey` CHAR(36) NOT NULL COMMENT 'Polymorphic',
  `MaleJumpPKey` CHAR(36) NOT NULL COMMENT 'Polymorphic',
  `MaleThrowPKey` CHAR(36) NOT NULL COMMENT 'Polymorphic',
  `MaleMiddleDistancePKey` CHAR(36) NOT NULL COMMENT 'Polymorphic',
  `FemaleSprintPKey` CHAR(36) NOT NULL COMMENT 'Polymorphic',
  `FemaleJumpPKey` CHAR(36) NOT NULL COMMENT 'Polymorphic',
  `FemaleThrowPKey` CHAR(36) NOT NULL COMMENT 'Polymorphic',
  `FemaleMiddleDistancePKey` CHAR(36) NOT NULL COMMENT 'Polymorphic',
  PRIMARY KEY (`CoursePKey`, `Year`),
  CONSTRAINT `CoursePKey`
    FOREIGN KEY (`CoursePKey`)
    REFERENCES `bjs`.`Course` (`PKey`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;
CREATE INDEX `CoursePKeyINDEX` ON `bjs`.`DisciplineMeta` (`CoursePKey` ASC);

SHOW WARNINGS;
CREATE INDEX `YearINDEX` ON `bjs`.`DisciplineMeta` (`Year` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bjs`.`CompetitionDiscipline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjs`.`CompetitionDiscipline` (
  `PKey` CHAR(36) NOT NULL,
  `Type` ENUM('Sprint','Jump','Throw','MiddleDistance') NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Unit` VARCHAR(25) NOT NULL,
  `LowIsBetter` TINYINT(1) NOT NULL,
  PRIMARY KEY (`PKey`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Name_UNIQUE` ON `bjs`.`CompetitionDiscipline` (`Name` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bjs`.`TraditionalDiscipline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjs`.`TraditionalDiscipline` (
  `PKey` CHAR(36) NOT NULL,
  `Type` ENUM('Sprint','Jump','Throw','MiddleDistance') NOT NULL,
  `Sex` ENUM('Male','Female') NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `UnitSymbol` CHAR(1) NOT NULL,
  `Distance` INT(4) NULL,
  `Overhead` FLOAT(3,2) NULL,
  `ConstantA` FLOAT(6,5) NOT NULL,
  `ConstantC` FLOAT(7,6) NOT NULL,
  `Measurement` ENUM('Manual','Electronic') NULL,
  PRIMARY KEY (`PKey`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bjs`.`StudentCourseRel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjs`.`StudentCourseRel` (
  `StudentPKey` CHAR(36) NOT NULL,
  `CoursePKey` CHAR(36) NOT NULL,
  `Year` YEAR NOT NULL,
  PRIMARY KEY (`StudentPKey`, `CoursePKey`),
  CONSTRAINT `fk_Course_has_Student_Course1`
    FOREIGN KEY (`CoursePKey`)
    REFERENCES `bjs`.`Course` (`PKey`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Course_has_Student_Student1`
    FOREIGN KEY (`StudentPKey`)
    REFERENCES `bjs`.`Student` (`PKey`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;
CREATE INDEX `StudentPKeyINDEX` ON `bjs`.`StudentCourseRel` (`StudentPKey` ASC);

SHOW WARNINGS;
CREATE INDEX `CoursePKeyINDEX` ON `bjs`.`StudentCourseRel` (`CoursePKey` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `StudentPKeyYearUNIQUE` ON `bjs`.`StudentCourseRel` (`StudentPKey` ASC, `Year` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bjs`.`CompetitionReportMeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjs`.`CompetitionReportMeta` (
  `Year` YEAR NOT NULL,
  `HonoraryCertificatePercentage` INT(3) NOT NULL,
  `VictoryCertificatePercentage` INT(3) NOT NULL,
  `Grade1Percentage` INT(3) NOT NULL,
  `Grade2Percentage` INT(3) NOT NULL,
  `Grade3Percentage` INT(3) NOT NULL,
  `Grade4Percentage` INT(3) NOT NULL,
  `Grade5Percentage` INT(3) NOT NULL,
  PRIMARY KEY (`Year`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bjs`.`TraditionalReportMeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjs`.`TraditionalReportMeta` (
  `PKey` CHAR(36) NOT NULL,
  `Sex` ENUM('Male','Female') NOT NULL,
  `Age` INT(2) ZEROFILL NOT NULL,
  `HonoraryCertificateScore` INT(4) NOT NULL,
  `VictoryCertificateScore` INT(4) NOT NULL,
  PRIMARY KEY (`PKey`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `SexAgeUNIQUE` ON `bjs`.`TraditionalReportMeta` (`Sex` ASC, `Age` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `bjs`.`TraditionalDiscipline`
-- -----------------------------------------------------
START TRANSACTION;
USE `bjs`;
INSERT INTO `bjs`.`TraditionalDiscipline` (`PKey`, `Type`, `Sex`, `Name`, `UnitSymbol`, `Distance`, `Overhead`, `ConstantA`, `ConstantC`, `Measurement`) VALUES ('9a72a264-7e72-11e4-bf87-00249b0f3387', 'Sprint', 'Female', 'Sprint 50 m', 's', 50, 0.24, 3.64800, 0.00660, 'Manual');
INSERT INTO `bjs`.`TraditionalDiscipline` (`PKey`, `Type`, `Sex`, `Name`, `UnitSymbol`, `Distance`, `Overhead`, `ConstantA`, `ConstantC`, `Measurement`) VALUES ('80927ffb-7f27-11e4-bf87-00249b0f3387', 'Sprint', 'Female', 'Sprint 75 m', 's', 75, 0.24, 3.99800, 0.00660, 'Manual');
INSERT INTO `bjs`.`TraditionalDiscipline` (`PKey`, `Type`, `Sex`, `Name`, `UnitSymbol`, `Distance`, `Overhead`, `ConstantA`, `ConstantC`, `Measurement`) VALUES ('cd48a79b-4ded-4de1-badb-795dd7a2c5dd', 'Sprint', 'Female', 'Sprint 100 m', 's', 100, 0.24, 4.00620, 0.00656, 'Manual');
INSERT INTO `bjs`.`TraditionalDiscipline` (`PKey`, `Type`, `Sex`, `Name`, `UnitSymbol`, `Distance`, `Overhead`, `ConstantA`, `ConstantC`, `Measurement`) VALUES ('cfaccaf6-10c9-42b4-9c4e-fc53d59b09ad', 'Sprint', 'Female', 'Sprint 50 m', 's', 50, NULL, 3.64800, 0.00660, 'Electronic');
INSERT INTO `bjs`.`TraditionalDiscipline` (`PKey`, `Type`, `Sex`, `Name`, `UnitSymbol`, `Distance`, `Overhead`, `ConstantA`, `ConstantC`, `Measurement`) VALUES ('b68cb942-8826-4938-abce-9b1bf2cee550', 'Sprint', 'Female', 'Sprint 75 m', 's', 75, NULL, 3.99800, 0.00660, 'Electronic');
INSERT INTO `bjs`.`TraditionalDiscipline` (`PKey`, `Type`, `Sex`, `Name`, `UnitSymbol`, `Distance`, `Overhead`, `ConstantA`, `ConstantC`, `Measurement`) VALUES ('02e7bcb5-fbbf-421e-bad7-d2b3190ed2ca', 'Sprint', 'Female', 'Sprint 100 m', 's', 100, NULL, 4.00620, 0.00656, 'Electronic');
INSERT INTO `bjs`.`TraditionalDiscipline` (`PKey`, `Type`, `Sex`, `Name`, `UnitSymbol`, `Distance`, `Overhead`, `ConstantA`, `ConstantC`, `Measurement`) VALUES ('bfe57845-d9d2-4d33-9ca9-d8ac82d1dca6', 'MiddleDistance', 'Female', 'Lauf 800 m', 's', 800, NULL, 2.02320, 0.00647, NULL);
INSERT INTO `bjs`.`TraditionalDiscipline` (`PKey`, `Type`, `Sex`, `Name`, `UnitSymbol`, `Distance`, `Overhead`, `ConstantA`, `ConstantC`, `Measurement`) VALUES ('fc40a2c0-46cc-42d6-bd56-f11e7f4954d1', 'MiddleDistance', 'Female', 'Lauf 2000 m', 's', 2000, NULL, 1.80000, 0.00540, NULL);
INSERT INTO `bjs`.`TraditionalDiscipline` (`PKey`, `Type`, `Sex`, `Name`, `UnitSymbol`, `Distance`, `Overhead`, `ConstantA`, `ConstantC`, `Measurement`) VALUES ('587b637d-5e4d-4a2d-bb1c-9641b83a7a08', 'MiddleDistance', 'Female', 'Lauf 3000 m', 's', 3000, NULL, 1.75000, 0.00500, NULL);
INSERT INTO `bjs`.`TraditionalDiscipline` (`PKey`, `Type`, `Sex`, `Name`, `UnitSymbol`, `Distance`, `Overhead`, `ConstantA`, `ConstantC`, `Measurement`) VALUES ('953d6cb3-501b-4a02-99da-f1a86edb636f', 'Jump', 'Female', 'Hochsprung', 'm', NULL, NULL, 0.88070, 0.00068, NULL);
INSERT INTO `bjs`.`TraditionalDiscipline` (`PKey`, `Type`, `Sex`, `Name`, `UnitSymbol`, `Distance`, `Overhead`, `ConstantA`, `ConstantC`, `Measurement`) VALUES ('24d9b5dd-3513-416c-a126-349ac2dcb781', 'Jump', 'Female', 'Weitsprung', 'm', NULL, NULL, 1.09350, 0.00208, NULL);
INSERT INTO `bjs`.`TraditionalDiscipline` (`PKey`, `Type`, `Sex`, `Name`, `UnitSymbol`, `Distance`, `Overhead`, `ConstantA`, `ConstantC`, `Measurement`) VALUES ('138b08a4-940c-4633-9537-027a58df115d', 'Throw', 'Female', 'Kugelstoß', 'm', NULL, NULL, 1.27900, 0.00398, NULL);
INSERT INTO `bjs`.`TraditionalDiscipline` (`PKey`, `Type`, `Sex`, `Name`, `UnitSymbol`, `Distance`, `Overhead`, `ConstantA`, `ConstantC`, `Measurement`) VALUES ('bb4fdf4d-e832-491c-aa62-af0e693155d5', 'Throw', 'Female', 'Schleuderball', 'm', NULL, NULL, 1.08500, 0.00921, NULL);
INSERT INTO `bjs`.`TraditionalDiscipline` (`PKey`, `Type`, `Sex`, `Name`, `UnitSymbol`, `Distance`, `Overhead`, `ConstantA`, `ConstantC`, `Measurement`) VALUES ('0dcf6e43-e4d3-4dae-8966-8ce805dbb64e', 'Throw', 'Female', '200-g-Ballwurf', 'm', NULL, NULL, 1.41490, 0.01039, NULL);
INSERT INTO `bjs`.`TraditionalDiscipline` (`PKey`, `Type`, `Sex`, `Name`, `UnitSymbol`, `Distance`, `Overhead`, `ConstantA`, `ConstantC`, `Measurement`) VALUES ('b101f80e-cea6-4c81-99f6-1ba5643f6c70', 'Throw', 'Female', '80-g-Schlagballwurf', 'm', NULL, NULL, 2.02320, 0.00874, NULL);
INSERT INTO `bjs`.`TraditionalDiscipline` (`PKey`, `Type`, `Sex`, `Name`, `UnitSymbol`, `Distance`, `Overhead`, `ConstantA`, `ConstantC`, `Measurement`) VALUES ('ac62b909-c533-470a-9eb8-744d2b9cc013', 'Sprint', 'Male', 'Sprint 50 m', 's', 50, 0.24, 3.79000, 0.00690, 'Manual');
INSERT INTO `bjs`.`TraditionalDiscipline` (`PKey`, `Type`, `Sex`, `Name`, `UnitSymbol`, `Distance`, `Overhead`, `ConstantA`, `ConstantC`, `Measurement`) VALUES ('7205b19a-6036-4dad-a1a1-ccee7ea48584', 'Sprint', 'Male', 'Sprint 75 m', 's', 75, 0.24, 4.10000, 0.00664, 'Manual');
INSERT INTO `bjs`.`TraditionalDiscipline` (`PKey`, `Type`, `Sex`, `Name`, `UnitSymbol`, `Distance`, `Overhead`, `ConstantA`, `ConstantC`, `Measurement`) VALUES ('9f6f0333-b70e-4d55-98c0-67057decbee0', 'Sprint', 'Male', 'Sprint 100 m', 's', 100, 0.24, 4.34100, 0.00676, 'Manual');
INSERT INTO `bjs`.`TraditionalDiscipline` (`PKey`, `Type`, `Sex`, `Name`, `UnitSymbol`, `Distance`, `Overhead`, `ConstantA`, `ConstantC`, `Measurement`) VALUES ('b16745e2-bbba-4346-8d49-7d9d65e7ecd6', 'Sprint', 'Male', 'Sprint 50 m', 's', 50, NULL, 3.79000, 0.00690, 'Electronic');
INSERT INTO `bjs`.`TraditionalDiscipline` (`PKey`, `Type`, `Sex`, `Name`, `UnitSymbol`, `Distance`, `Overhead`, `ConstantA`, `ConstantC`, `Measurement`) VALUES ('99144998-865d-47c7-8d45-552998349254', 'Sprint', 'Male', 'Sprint 75 m', 's', 75, NULL, 4.10000, 0.00664, 'Electronic');
INSERT INTO `bjs`.`TraditionalDiscipline` (`PKey`, `Type`, `Sex`, `Name`, `UnitSymbol`, `Distance`, `Overhead`, `ConstantA`, `ConstantC`, `Measurement`) VALUES ('c3300949-30fe-41a5-84bc-46ae791bf062', 'Sprint', 'Male', 'Sprint 100 m', 's', 100, NULL, 4.34100, 0.00676, 'Electronic');
INSERT INTO `bjs`.`TraditionalDiscipline` (`PKey`, `Type`, `Sex`, `Name`, `UnitSymbol`, `Distance`, `Overhead`, `ConstantA`, `ConstantC`, `Measurement`) VALUES ('48742630-8e5b-41d0-934c-f4a58e8227f4', 'MiddleDistance', 'Male', 'Lauf 1000 m', 's', 1000, NULL, 2.15800, 0.00600, NULL);
INSERT INTO `bjs`.`TraditionalDiscipline` (`PKey`, `Type`, `Sex`, `Name`, `UnitSymbol`, `Distance`, `Overhead`, `ConstantA`, `ConstantC`, `Measurement`) VALUES ('cb418b3b-3293-43f2-9a28-d6acfef81734', 'MiddleDistance', 'Male', 'Lauf 2000 m', 's', 2000, NULL, 1.78400, 0.00600, NULL);
INSERT INTO `bjs`.`TraditionalDiscipline` (`PKey`, `Type`, `Sex`, `Name`, `UnitSymbol`, `Distance`, `Overhead`, `ConstantA`, `ConstantC`, `Measurement`) VALUES ('426231f9-6f68-43d2-877f-2760ed6ab068', 'MiddleDistance', 'Male', 'Lauf 3000 m', 's', 3000, NULL, 1.70000, 0.00580, NULL);
INSERT INTO `bjs`.`TraditionalDiscipline` (`PKey`, `Type`, `Sex`, `Name`, `UnitSymbol`, `Distance`, `Overhead`, `ConstantA`, `ConstantC`, `Measurement`) VALUES ('0a18a585-a888-4993-83a0-342afea368c2', 'Jump', 'Male', 'Hochsprung', 'm', NULL, NULL, 0.84100, 0.00080, NULL);
INSERT INTO `bjs`.`TraditionalDiscipline` (`PKey`, `Type`, `Sex`, `Name`, `UnitSymbol`, `Distance`, `Overhead`, `ConstantA`, `ConstantC`, `Measurement`) VALUES ('25ce654a-68dd-4094-b2b6-737581fb8957', 'Jump', 'Male', 'Weitsprung', 'm', NULL, NULL, 1.15028, 0.00219, NULL);
INSERT INTO `bjs`.`TraditionalDiscipline` (`PKey`, `Type`, `Sex`, `Name`, `UnitSymbol`, `Distance`, `Overhead`, `ConstantA`, `ConstantC`, `Measurement`) VALUES ('0560491e-f326-483b-974f-6d07b967d427', 'Throw', 'Male', 'Kugelstoß', 'm', NULL, NULL, 1.42500, 0.00370, NULL);
INSERT INTO `bjs`.`TraditionalDiscipline` (`PKey`, `Type`, `Sex`, `Name`, `UnitSymbol`, `Distance`, `Overhead`, `ConstantA`, `ConstantC`, `Measurement`) VALUES ('e000cca7-8ab0-4c5c-bf15-c2fef424efd6', 'Throw', 'Male', 'Schleuderball', 'm', NULL, NULL, 1.59500, 0.009125, NULL);
INSERT INTO `bjs`.`TraditionalDiscipline` (`PKey`, `Type`, `Sex`, `Name`, `UnitSymbol`, `Distance`, `Overhead`, `ConstantA`, `ConstantC`, `Measurement`) VALUES ('55597498-82e2-4f02-be94-5c766e599935', 'Throw', 'Male', '200-g-Ballwurf', 'm', NULL, NULL, 1.93600, 0.01240, NULL);
INSERT INTO `bjs`.`TraditionalDiscipline` (`PKey`, `Type`, `Sex`, `Name`, `UnitSymbol`, `Distance`, `Overhead`, `ConstantA`, `ConstantC`, `Measurement`) VALUES ('b82a9905-cc00-40a8-87af-0d94b1f72cda', 'Throw', 'Male', '80-g-Schlagballwurf', 'm', NULL, NULL, 2.80000, 0.01100, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `bjs`.`TraditionalReportMeta`
-- -----------------------------------------------------
START TRANSACTION;
USE `bjs`;
INSERT INTO `bjs`.`TraditionalReportMeta` (`PKey`, `Sex`, `Age`, `HonoraryCertificateScore`, `VictoryCertificateScore`) VALUES ('8289c7bc-960a-4bc0-8bef-a06dbee80459', 'Female', 08, 625, 475);
INSERT INTO `bjs`.`TraditionalReportMeta` (`PKey`, `Sex`, `Age`, `HonoraryCertificateScore`, `VictoryCertificateScore`) VALUES ('fc1b97e0-2946-4b85-a2a9-ae864ef8adf7', 'Female', 09, 725, 550);
INSERT INTO `bjs`.`TraditionalReportMeta` (`PKey`, `Sex`, `Age`, `HonoraryCertificateScore`, `VictoryCertificateScore`) VALUES ('e12ca7bb-bc8a-4c94-9dbc-001a7b2ad59f', 'Female', 10, 825, 625);
INSERT INTO `bjs`.`TraditionalReportMeta` (`PKey`, `Sex`, `Age`, `HonoraryCertificateScore`, `VictoryCertificateScore`) VALUES ('40d2abbb-9f4e-4651-a87c-afbd481cd165', 'Female', 11, 900, 700);
INSERT INTO `bjs`.`TraditionalReportMeta` (`PKey`, `Sex`, `Age`, `HonoraryCertificateScore`, `VictoryCertificateScore`) VALUES ('dd634026-f207-4833-ad33-7e21f36cf7ee', 'Female', 12, 975, 775);
INSERT INTO `bjs`.`TraditionalReportMeta` (`PKey`, `Sex`, `Age`, `HonoraryCertificateScore`, `VictoryCertificateScore`) VALUES ('7143df0f-9211-4238-b1d2-aa3f6957bbc0', 'Female', 13, 1025, 825);
INSERT INTO `bjs`.`TraditionalReportMeta` (`PKey`, `Sex`, `Age`, `HonoraryCertificateScore`, `VictoryCertificateScore`) VALUES ('cc927219-030c-4a03-98d6-eaaffce5959a', 'Female', 14, 1050, 850);
INSERT INTO `bjs`.`TraditionalReportMeta` (`PKey`, `Sex`, `Age`, `HonoraryCertificateScore`, `VictoryCertificateScore`) VALUES ('7bfa22c2-d48a-4c91-a946-a4dbb33f32cc', 'Female', 15, 1075, 875);
INSERT INTO `bjs`.`TraditionalReportMeta` (`PKey`, `Sex`, `Age`, `HonoraryCertificateScore`, `VictoryCertificateScore`) VALUES ('c02347fd-b640-4841-b1c2-2b0b6e52fdd9', 'Female', 16, 1100, 900);
INSERT INTO `bjs`.`TraditionalReportMeta` (`PKey`, `Sex`, `Age`, `HonoraryCertificateScore`, `VictoryCertificateScore`) VALUES ('a12347d4-0b50-4682-ba0f-e59d92945bf0', 'Female', 17, 1125, 925);
INSERT INTO `bjs`.`TraditionalReportMeta` (`PKey`, `Sex`, `Age`, `HonoraryCertificateScore`, `VictoryCertificateScore`) VALUES ('4e2a0780-51cf-440a-b5aa-ca69b6b26b9f', 'Female', 18, 1150, 950);
INSERT INTO `bjs`.`TraditionalReportMeta` (`PKey`, `Sex`, `Age`, `HonoraryCertificateScore`, `VictoryCertificateScore`) VALUES ('b0380ba0-0084-4fa8-b4d2-66ceb47f7de3', 'Male', 08, 575, 450);
INSERT INTO `bjs`.`TraditionalReportMeta` (`PKey`, `Sex`, `Age`, `HonoraryCertificateScore`, `VictoryCertificateScore`) VALUES ('e97eb114-c7b2-4c3e-9044-99bb04897824', 'Male', 09, 675, 525);
INSERT INTO `bjs`.`TraditionalReportMeta` (`PKey`, `Sex`, `Age`, `HonoraryCertificateScore`, `VictoryCertificateScore`) VALUES ('1ebc5e7d-ec86-4dcf-81c8-1a7e221a975b', 'Male', 10, 775, 600);
INSERT INTO `bjs`.`TraditionalReportMeta` (`PKey`, `Sex`, `Age`, `HonoraryCertificateScore`, `VictoryCertificateScore`) VALUES ('8ad75e1d-da87-4d74-8c31-2aad5e78ca84', 'Male', 11, 875, 675);
INSERT INTO `bjs`.`TraditionalReportMeta` (`PKey`, `Sex`, `Age`, `HonoraryCertificateScore`, `VictoryCertificateScore`) VALUES ('6d415c15-2a06-47b8-819e-fdc61a5c988b', 'Male', 12, 975, 750);
INSERT INTO `bjs`.`TraditionalReportMeta` (`PKey`, `Sex`, `Age`, `HonoraryCertificateScore`, `VictoryCertificateScore`) VALUES ('47e90afd-953c-4ebf-ab17-834d2ca26467', 'Male', 13, 1050, 825);
INSERT INTO `bjs`.`TraditionalReportMeta` (`PKey`, `Sex`, `Age`, `HonoraryCertificateScore`, `VictoryCertificateScore`) VALUES ('a2d5fb6b-13da-453f-ac3b-d92d1895e708', 'Male', 14, 1125, 900);
INSERT INTO `bjs`.`TraditionalReportMeta` (`PKey`, `Sex`, `Age`, `HonoraryCertificateScore`, `VictoryCertificateScore`) VALUES ('9bea4fb4-ba32-4c7f-9b7b-a003825b7471', 'Male', 15, 1225, 975);
INSERT INTO `bjs`.`TraditionalReportMeta` (`PKey`, `Sex`, `Age`, `HonoraryCertificateScore`, `VictoryCertificateScore`) VALUES ('d895f448-ec5b-49cc-b56f-8ac716f18945', 'Male', 16, 1325, 1050);
INSERT INTO `bjs`.`TraditionalReportMeta` (`PKey`, `Sex`, `Age`, `HonoraryCertificateScore`, `VictoryCertificateScore`) VALUES ('13c6c0d2-76f1-49b1-9ee3-146aef697b68', 'Male', 17, 1400, 1125);
INSERT INTO `bjs`.`TraditionalReportMeta` (`PKey`, `Sex`, `Age`, `HonoraryCertificateScore`, `VictoryCertificateScore`) VALUES ('c014bbc4-71f7-426d-a689-263d5569141f', 'Male', 18, 1475, 1200);
INSERT INTO `bjs`.`TraditionalReportMeta` (`PKey`, `Sex`, `Age`, `HonoraryCertificateScore`, `VictoryCertificateScore`) VALUES ('2d859676-dd11-4265-8988-1dfa8d1fc966', 'Male', 19, 1550, 1275);

COMMIT;

