//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HonglornBL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HonglornBL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///
        ///&lt;ArrayOfHandicap xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;Handicap&gt;
        ///    &lt;PKey&gt;D7F0B283-20F2-4167-B145-AE0D377E2910&lt;/PKey&gt;
        ///    &lt;Name&gt;A 1&lt;/Name&gt;
        ///  &lt;/Handicap&gt;
        ///  &lt;Handicap&gt;
        ///    &lt;PKey&gt;0F93BB28-3F2C-44F1-96C0-568B8E9D943F&lt;/PKey&gt;
        ///    &lt;Name&gt;A 2&lt;/Name&gt;
        ///  &lt;/Handicap&gt;
        ///  &lt;Handicap&gt;
        ///    &lt;PKey&gt;65758571-7B9A-48BB-8A4B-0D66C72950A7&lt;/PKey&gt;
        ///    &lt;Name&gt;A 3&lt;/Name&gt;
        ///  &lt;/Handicap&gt;
        ///  &lt;Handicap&gt;
        ///    &lt;PKey&gt;BA9F2D1A-842D-428D-A744-ACAE02437E04&lt;/PKey&gt;
        ///    &lt;Name&gt;A 4&lt;/Name&gt;
        ///  &lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ArrayOfHandicap {
            get {
                return ResourceManager.GetString("ArrayOfHandicap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///
        ///&lt;ArrayOfTraditionalReportMeta xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;TraditionalReportMeta&gt;
        ///    &lt;Sex&gt;Female&lt;/Sex&gt;
        ///    &lt;Age&gt;8&lt;/Age&gt;
        ///    &lt;HonoraryCertificateScore&gt;625&lt;/HonoraryCertificateScore&gt;
        ///    &lt;VictoryCertificateScore&gt;475&lt;/VictoryCertificateScore&gt;
        ///  &lt;/TraditionalReportMeta&gt;
        ///  &lt;TraditionalReportMeta&gt;
        ///    &lt;Sex&gt;Female&lt;/Sex&gt;
        ///    &lt;Age&gt;9&lt;/Age&gt;
        ///    &lt;HonoraryCertificateScore&gt;725&lt;/HonoraryCertificateScore&gt;
        ///    &lt;VictoryCertificateScore&gt;550&lt;/VictoryCertificate [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ArrayOfTraditionalReportMeta {
            get {
                return ResourceManager.GetString("ArrayOfTraditionalReportMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///
        ///&lt;ArrayOfTraditionalTrackAndFieldDisciplineHandicap xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;TraditionalTrackAndFieldDisciplineHandicap&gt;
        ///    &lt;DisciplinePKey&gt;FE237B12-41BD-4E0F-A825-0573F61598F7&lt;/DisciplinePKey&gt;
        ///    &lt;HandicapPKey&gt;D7F0B283-20F2-4167-B145-AE0D377E2910&lt;/HandicapPKey&gt;
        ///    &lt;Sex&gt;Male&lt;/Sex&gt;
        ///    &lt;Factor&gt;1.05&lt;/Factor&gt;
        ///  &lt;/TraditionalTrackAndFieldDisciplineHandicap&gt;
        ///  &lt;TraditionalTrackAndFieldDisciplineHandicap&gt;
        ///    &lt;DisciplinePKey&gt;FE237B12-41BD-4E0F-A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ArrayOfTraditionalTrackAndFieldDisciplineHandicap {
            get {
                return ResourceManager.GetString("ArrayOfTraditionalTrackAndFieldDisciplineHandicap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///
        ///&lt;ArrayOfTraditionalTrackAndFieldJumpDiscipline xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;TraditionalTrackAndFieldJumpDiscipline&gt;
        ///    &lt;PKey&gt;FE237B12-41BD-4E0F-A825-0573F61598F7&lt;/PKey&gt;
        ///    &lt;Name&gt;Hochsprung&lt;/Name&gt;
        ///    &lt;Unit&gt;m&lt;/Unit&gt;
        ///    &lt;Sex&gt;Female&lt;/Sex&gt;
        ///    &lt;ConstantA&gt;0.8807&lt;/ConstantA&gt;
        ///    &lt;ConstantC&gt;0.00068&lt;/ConstantC&gt;
        ///  &lt;/TraditionalTrackAndFieldJumpDiscipline&gt;
        ///  &lt;TraditionalTrackAndFieldJumpDiscipline&gt;
        ///    &lt;PKey&gt;BDD3DDC4-771A-48AF-A374-101A0248FC8C&lt;/PKey [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ArrayOfTraditionalTrackAndFieldJumpDiscipline {
            get {
                return ResourceManager.GetString("ArrayOfTraditionalTrackAndFieldJumpDiscipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///
        ///&lt;ArrayOfTraditionalTrackAndFieldMiddleDistanceDiscipline xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;TraditionalTrackAndFieldMiddleDistanceDiscipline&gt;
        ///    &lt;Name&gt;Lauf 2000 m&lt;/Name&gt;
        ///    &lt;Sex&gt;Male&lt;/Sex&gt;
        ///    &lt;Distance&gt;2000&lt;/Distance&gt;
        ///    &lt;ConstantA&gt;1.784&lt;/ConstantA&gt;
        ///    &lt;ConstantC&gt;0.006&lt;/ConstantC&gt;
        ///  &lt;/TraditionalTrackAndFieldMiddleDistanceDiscipline&gt;
        ///  &lt;TraditionalTrackAndFieldMiddleDistanceDiscipline&gt;
        ///    &lt;Name&gt;Lauf 800 m&lt;/Name&gt;
        ///    &lt;Sex&gt;Female&lt;/Sex&gt;
        ///    &lt;Dis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ArrayOfTraditionalTrackAndFieldMiddleDistanceDiscipline {
            get {
                return ResourceManager.GetString("ArrayOfTraditionalTrackAndFieldMiddleDistanceDiscipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///
        ///&lt;ArrayOfTraditionalTrackAndFieldSprintDiscipline xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;TraditionalTrackAndFieldSprintDiscipline&gt;
        ///    &lt;Name&gt;Sprint 100 m&lt;/Name&gt;
        ///    &lt;Sex&gt;Female&lt;/Sex&gt;
        ///    &lt;Distance&gt;100&lt;/Distance&gt;
        ///    &lt;Overhead xsi:nil=&quot;true&quot; /&gt;
        ///    &lt;ConstantA&gt;4.0062&lt;/ConstantA&gt;
        ///    &lt;ConstantC&gt;0.00656&lt;/ConstantC&gt;
        ///    &lt;Measurement&gt;Electronic&lt;/Measurement&gt;
        ///  &lt;/TraditionalTrackAndFieldSprintDiscipline&gt;
        ///  &lt;TraditionalTrackAndFieldSprintDiscipline&gt;
        ///    &lt;Name&gt;S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ArrayOfTraditionalTrackAndFieldSprintDiscipline {
            get {
                return ResourceManager.GetString("ArrayOfTraditionalTrackAndFieldSprintDiscipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///
        ///&lt;ArrayOfTraditionalTrackAndFieldThrowDiscipline xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;TraditionalTrackAndFieldThrowDiscipline&gt;
        ///    &lt;Name&gt;80-g-Schlagballwurf&lt;/Name&gt;
        ///    &lt;Sex&gt;Male&lt;/Sex&gt;
        ///    &lt;ConstantA&gt;2.8&lt;/ConstantA&gt;
        ///    &lt;ConstantC&gt;0.011&lt;/ConstantC&gt;
        ///  &lt;/TraditionalTrackAndFieldThrowDiscipline&gt;
        ///  &lt;TraditionalTrackAndFieldThrowDiscipline&gt;
        ///    &lt;Name&gt;Schleuderball&lt;/Name&gt;
        ///    &lt;Sex&gt;Female&lt;/Sex&gt;
        ///    &lt;ConstantA&gt;1.085&lt;/ConstantA&gt;
        ///    &lt;ConstantC&gt;0.00921&lt;/Constant [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ArrayOfTraditionalTrackAndFieldThrowDiscipline {
            get {
                return ResourceManager.GetString("ArrayOfTraditionalTrackAndFieldThrowDiscipline", resourceCulture);
            }
        }
    }
}
