//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HonglornBL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HonglornBL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///
        ///&lt;ArrayOfHandicap xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;Handicap&gt;
        ///    &lt;Name&gt;A 1&lt;/Name&gt;
        ///  &lt;/Handicap&gt;
        ///&lt;/ArrayOfHandicap&gt;.
        /// </summary>
        internal static string ArrayOfHandicap {
            get {
                return ResourceManager.GetString("ArrayOfHandicap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///
        ///&lt;ArrayOfTraditionalDiscipline xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;TraditionalDiscipline&gt;
        ///    &lt;Type&gt;Sprint&lt;/Type&gt;
        ///    &lt;Name&gt;Sprint 100 m&lt;/Name&gt;
        ///    &lt;Unit&gt;s&lt;/Unit&gt;
        ///    &lt;Sex&gt;Female&lt;/Sex&gt;
        ///    &lt;Distance&gt;100&lt;/Distance&gt;
        ///    &lt;Overhead xsi:nil=&quot;true&quot; /&gt;
        ///    &lt;ConstantA&gt;4.0062&lt;/ConstantA&gt;
        ///    &lt;ConstantC&gt;0.00656&lt;/ConstantC&gt;
        ///    &lt;Measurement&gt;Electronic&lt;/Measurement&gt;
        ///  &lt;/TraditionalDiscipline&gt;
        ///  &lt;TraditionalDiscipline&gt;
        ///    &lt;Type&gt;Sprint&lt;/Type&gt;
        ///    &lt;Name&gt;Sprint  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ArrayOfTraditionalDiscipline {
            get {
                return ResourceManager.GetString("ArrayOfTraditionalDiscipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///
        ///&lt;ArrayOfTraditionalReportMeta xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;TraditionalReportMeta&gt;
        ///    &lt;Sex&gt;Female&lt;/Sex&gt;
        ///    &lt;Age&gt;8&lt;/Age&gt;
        ///    &lt;HonoraryCertificateScore&gt;625&lt;/HonoraryCertificateScore&gt;
        ///    &lt;VictoryCertificateScore&gt;475&lt;/VictoryCertificateScore&gt;
        ///  &lt;/TraditionalReportMeta&gt;
        ///  &lt;TraditionalReportMeta&gt;
        ///    &lt;Sex&gt;Female&lt;/Sex&gt;
        ///    &lt;Age&gt;9&lt;/Age&gt;
        ///    &lt;HonoraryCertificateScore&gt;725&lt;/HonoraryCertificateScore&gt;
        ///    &lt;VictoryCertificateScore&gt;550&lt;/VictoryCertificate [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ArrayOfTraditionalReportMeta {
            get {
                return ResourceManager.GetString("ArrayOfTraditionalReportMeta", resourceCulture);
            }
        }
    }
}
